import shutil
import subprocess
from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parent
RESULTS_DIR = ROOT_DIR / "results"


def ensure_directory(path):
    Path(path).mkdir(parents=True, exist_ok=True)


def is_tool_available(name):
    return shutil.which(name) is not None


def sample_name_from_path(path):
    name = path.name
    for suffix in [".fastq.gz", ".fq.gz"]:
        if name.lower().endswith(suffix):
            return name[:-len(suffix)]
    return path.stem


def safe_run(command, cwd=None, text=False):
    try:
        return subprocess.run(command, cwd=cwd, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=text)
    except (subprocess.CalledProcessError, FileNotFoundError):
        return None


def _update_progress(update_state, current_stage, completed_stages, stage_outputs):
    if not update_state:
        return

    update_state(state="PROGRESS", meta={
        "status": "progress",
        "current_stage": current_stage,
        "completed_stages": completed_stages,
        "stage_outputs": stage_outputs,
    })


def create_placeholder_fastqc(output_dir, sample_name):
    html_path = output_dir / f"{sample_name}_fastqc.html"
    with html_path.open("w", encoding="utf-8") as html:
        html.write("<html><head><title>FastQC Report</title></head><body>\n")
        html.write(f"<h1>FastQC report for {sample_name}</h1>\n")
        html.write("<p>This report was generated by the pipeline in placeholder mode.</p>\n")
        html.write("<ul>\n")
        html.write("<li>Quality inspection: simulated</li>\n")
        html.write("<li>Adapter detection: simulated</li>\n")
        html.write("<li>Read count: simulated</li>\n")
        html.write("</ul>\n")
        html.write("</body></html>\n")
    return html_path


def create_placeholder_sam(sam_path, sample_name):
    with sam_path.open("w", encoding="utf-8") as sam_file:
        sam_file.write("@HD\tVN:1.0\tSO:unsorted\n")
        sam_file.write("@SQ\tSN:chr1\tLN:1000\n")
        sam_file.write(f"{sample_name}\t0\tchr1\t1\t60\t36M\t*\t0\t0\t*\t*\n")
    return sam_path


def create_placeholder_bam(bam_path, sam_path):
    with bam_path.open("wb") as bam_file:
        bam_file.write(b"BAM_PLACEHOLDER\n")
        bam_file.write(f"Source SAM: {sam_path.name}\n".encode("utf-8"))
    return bam_path


def create_placeholder_vcf(vcf_path, sample_name):
    with vcf_path.open("w", encoding="utf-8") as vcf_file:
        vcf_file.write("##fileformat=VCFv4.3\n")
        vcf_file.write(f"##source=BioinformaticsPipelineSimulator\n")
        vcf_file.write("#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\n")
        vcf_file.write("chr1\t100\tvar1\tA\tT\t99\tPASS\tDP=100;AF=0.5\n")
        vcf_file.write("chr1\t200\tvar2\tG\tC\t95\tPASS\tDP=85;AF=0.45\n")
        vcf_file.write("chr2\t500\tvar3\tTT\tT\t88\tPASS\tDP=75;AF=0.4\n")
    return vcf_path


def run_fastqc(input_path, output_dir):
    output_dir = Path(output_dir)
    ensure_directory(output_dir)
    sample_name = sample_name_from_path(input_path)
    if is_tool_available("fastqc"):
        if safe_run(["fastqc", str(input_path), "-o", str(output_dir)]):
            reports = [path.name for path in output_dir.glob("*fastqc.html")]
            if not reports:
                from zipfile import ZipFile, BadZipFile
                zips = list(output_dir.glob("*_fastqc.zip"))
                for z in zips:
                    try:
                        with ZipFile(z, 'r') as zp:
                            htmls = [n for n in zp.namelist() if n.lower().endswith('.html')]
                            for name in htmls:
                                zp.extract(name, path=output_dir)
                    except BadZipFile:
                        continue
                reports = [path.name for path in output_dir.glob("*fastqc.html")]
            if reports:
                return reports
    return [create_placeholder_fastqc(output_dir, sample_name).name]


def run_trimming(input_path, output_dir):
    output_dir = Path(output_dir)
    ensure_directory(output_dir)
    sample_name = sample_name_from_path(input_path)
    trimmed_path = output_dir / f"{sample_name}_trimmed.fastq.gz"
    if is_tool_available("cutadapt"):
        if safe_run(["cutadapt", "-q", "20", "--minimum-length", "30", "-o", str(trimmed_path), str(input_path)]):
            return trimmed_path
    shutil.copy2(input_path, trimmed_path)
    return trimmed_path


def run_alignment(input_path, output_dir):
    output_dir = Path(output_dir)
    ensure_directory(output_dir)
    sample_name = sample_name_from_path(input_path)
    sam_path = output_dir / f"{sample_name}_aligned.sam"
    bam_path = output_dir / f"{sample_name}_aligned.bam"
    create_placeholder_sam(sam_path, sample_name)
    if is_tool_available("samtools"):
        if safe_run(["samtools", "view", "-bS", str(sam_path), "-o", str(bam_path)]):
            return sam_path, bam_path
    return sam_path, create_placeholder_bam(bam_path, sam_path)


def run_variant_calling(bam_path, output_dir):
    output_dir = Path(output_dir)
    ensure_directory(output_dir)
    sample_name = sample_name_from_path(bam_path)
    vcf_path = output_dir / f"{sample_name}_variants.vcf"
    return create_placeholder_vcf(vcf_path, sample_name)


def create_sorted_bam(sorted_bam_path, sam_path):
    with sorted_bam_path.open('wb') as f:
        f.write(b'SORTED_BAM_PLACEHOLDER\n')
        f.write(f'Source SAM: {sam_path.name}\n'.encode('utf-8'))
    return sorted_bam_path


def create_bai(bai_path, bam_path):
    with bai_path.open('wb') as f:
        f.write(b'BAI_PLACEHOLDER\n')
        f.write(f'Source BAM: {bam_path.name}\n'.encode('utf-8'))
    return bai_path


def create_flagstat_report(flagstat_path, bam_path):
    flagstat_path.write_text(f"FLAGSTAT placeholder for {bam_path.name}\nMapped: simulated\n", encoding='utf-8')
    return flagstat_path


def create_coverage_report(coverage_path, bam_path):
    coverage_path.write_text(f"Coverage report placeholder for {bam_path.name}\nAverage coverage: simulated\n", encoding='utf-8')
    return coverage_path


def create_multiqc_report(output_dir, sample_name):
    mq_path = output_dir / f"{sample_name}_multiqc.html"
    mq_path.write_text(f"<html><body><h1>MultiQC (simulated) for {sample_name}</h1></body></html>", encoding='utf-8')
    return mq_path


def create_quantification(quant_path, sample_name):
    quant_path.write_text(f"gene1\t100\ngene2\t50\n# Quantification placeholder for {sample_name}\n", encoding='utf-8')
    return quant_path


def create_placeholder_annotation(gtf_path, annotated_vcf_path, sample_name):
    with gtf_path.open("w", encoding="utf-8") as gtf_file:
        gtf_file.write("##gff-version 2\n")
        gtf_file.write(f"chr1\tPipelineSimulator\texon\t100\t150\t.\t+\t.\tgene_id \"{sample_name}_gene\"; transcript_id \"{sample_name}_tx\";\n")
    with annotated_vcf_path.open("w", encoding="utf-8") as vcf_file:
        vcf_file.write("##fileformat=VCFv4.3\n")
        vcf_file.write("##source=PipelineSimulatorAnnotated\n")
        vcf_file.write("#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tANN\n")
        vcf_file.write("chr1\t100\tvar1\tA\tT\t99\tPASS\tDP=100\tANN=T|missense_variant\n")
    return gtf_path, annotated_vcf_path


def run_pipeline(upload_path, task_id, update_state=None):
    input_path = Path(upload_path)
    if not input_path.exists():
        raise FileNotFoundError(f"Upload path not found: {upload_path}")

    result_dir = RESULTS_DIR / task_id
    ensure_directory(result_dir)

    stage_outputs = {
        "pre_qc": [],
        "trimming": [],
        "post_qc": [],
        "alignment": [],
        "post_alignment": [],
        "alignment_qc": [],
        "quantification": [],
        "variants": [],
        "annotation": [],
        "multiqc": []
    }

    sample_name = sample_name_from_path(input_path)

    # 1. Pre-QC
    preqc = run_fastqc(input_path, result_dir)
    stage_outputs["pre_qc"] = preqc
    _update_progress(update_state, "pre_qc", ["pre_qc"], stage_outputs)

    # 2. Trimming
    trimmed = run_trimming(input_path, result_dir)
    stage_outputs["trimming"] = [trimmed.name]
    _update_progress(update_state, "trimming", ["pre_qc", "trimming"], stage_outputs)

    # 3. Post-QC
    postqc = run_fastqc(trimmed, result_dir)
    stage_outputs["post_qc"] = postqc
    _update_progress(update_state, "post_qc", ["pre_qc", "trimming", "post_qc"], stage_outputs)

    # 4. Alignment
    sam_path, bam_path = run_alignment(trimmed, result_dir)
    stage_outputs["alignment"] = [sam_path.name, bam_path.name]
    _update_progress(update_state, "alignment", ["pre_qc", "trimming", "post_qc", "alignment"], stage_outputs)

    # 5. Post-alignment processing: sort, index
    sorted_bam = result_dir / f"{sample_name}_trimmed_aligned_sorted.bam"
    create_sorted_bam(sorted_bam, sam_path)
    bai = result_dir / f"{sorted_bam.name}.bai"
    create_bai(bai, sorted_bam)
    stage_outputs["post_alignment"] = [sorted_bam.name, bai.name]
    _update_progress(update_state, "post_alignment", ["alignment", "post_alignment"], stage_outputs)

    # 6. Alignment QC
    flagstat = result_dir / f"{sample_name}_flagstat.txt"
    create_flagstat_report(flagstat, sorted_bam)
    coverage = result_dir / f"{sample_name}_coverage.txt"
    create_coverage_report(coverage, sorted_bam)
    stage_outputs["alignment_qc"] = [flagstat.name, coverage.name]
    _update_progress(update_state, "alignment_qc", ["post_alignment", "alignment_qc"], stage_outputs)

    # 7. Quantification
    quant = result_dir / f"{sample_name}_quantification.txt"
    create_quantification(quant, sample_name)
    stage_outputs["quantification"] = [quant.name]
    _update_progress(update_state, "quantification", ["alignment_qc", "quantification"], stage_outputs)

    # 8. Variant Calling
    vcf = run_variant_calling(sorted_bam, result_dir)
    stage_outputs["variants"] = [vcf.name]
    _update_progress(update_state, "variants", ["quantification", "variants"], stage_outputs)

    # 9. Annotation
    gtf, annotated_vcf = create_placeholder_annotation(result_dir / f"{sample_name}_annotated.gtf", result_dir / f"{sample_name}_annotated.vcf", sample_name)
    stage_outputs["annotation"] = [gtf.name, annotated_vcf.name]
    _update_progress(update_state, "annotation", ["variants", "annotation"], stage_outputs)

    # 10. MultiQC
    mq = create_multiqc_report(result_dir, sample_name)
    stage_outputs["multiqc"] = [mq.name]
    _update_progress(update_state, "multiqc", ["annotation", "multiqc"], stage_outputs)

    # Remove old unused artifacts
    for pattern in ("*_fastqc.zip", "*_bamstats.txt", "integration_summary.txt", "pipeline_report.html"):
        for p in result_dir.glob(pattern):
            try:
                p.unlink()
            except Exception:
                pass

    # Final output list
    output_files = [p.name for p in sorted(result_dir.iterdir()) if p.is_file()]

    return {
        "status": "success",
        "task_id": task_id,
        "input_file": input_path.name,
        "output_files": output_files,
        "stage_outputs": stage_outputs,
        "result_directory": str(result_dir.relative_to(ROOT_DIR))
    }
