import shutil
import subprocess
from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parent
RESULTS_DIR = ROOT_DIR / "results"


def ensure_directory(path):
    Path(path).mkdir(parents=True, exist_ok=True)


def is_tool_available(name):
    return shutil.which(name) is not None


def sample_name_from_path(path):
    name = path.name
    for suffix in [".fastq.gz", ".fq.gz"]:
        if name.lower().endswith(suffix):
            return name[:-len(suffix)]
    return path.stem


def safe_run(command, cwd=None, text=False):
    try:
        return subprocess.run(command, cwd=cwd, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=text)
    except (subprocess.CalledProcessError, FileNotFoundError):
        return None


def _update_progress(update_state, current_stage, completed_stages, stage_outputs):
    if not update_state:
        return

    update_state(state="PROGRESS", meta={
        "status": "progress",
        "current_stage": current_stage,
        "completed_stages": completed_stages,
        "stage_outputs": stage_outputs,
    })


def create_placeholder_fastqc(output_dir, sample_name):
    html_path = output_dir / f"{sample_name}_fastqc.html"
    with html_path.open("w", encoding="utf-8") as html:
        html.write("<html><head><title>FastQC Report</title></head><body>\n")
        html.write(f"<h1>FastQC report for {sample_name}</h1>\n")
        html.write("<p>This report was generated by the pipeline in placeholder mode.</p>\n")
        html.write("<ul>\n")
        html.write("<li>Quality inspection: simulated</li>\n")
        html.write("<li>Adapter detection: simulated</li>\n")
        html.write("<li>Read count: simulated</li>\n")
        html.write("</ul>\n")
        html.write("</body></html>\n")
    return html_path


def create_placeholder_sam(sam_path, sample_name):
    with sam_path.open("w", encoding="utf-8") as sam_file:
        sam_file.write("@HD\tVN:1.0\tSO:unsorted\n")
        sam_file.write("@SQ\tSN:chr1\tLN:1000\n")
        sam_file.write(f"{sample_name}\t0\tchr1\t1\t60\t36M\t*\t0\t0\t*\t*\n")
    return sam_path


def create_placeholder_bam(bam_path, sam_path):
    with bam_path.open("wb") as bam_file:
        bam_file.write(b"BAM_PLACEHOLDER\n")
        bam_file.write(f"Source SAM: {sam_path.name}\n".encode("utf-8"))
    return bam_path


def create_placeholder_vcf(vcf_path, sample_name):
    with vcf_path.open("w", encoding="utf-8") as vcf_file:
        vcf_file.write("##fileformat=VCFv4.3\n")
        vcf_file.write(f"##source=BioinformaticsPipelineSimulator\n")
        vcf_file.write("#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\n")
        vcf_file.write("chr1\t100\tvar1\tA\tT\t99\tPASS\tDP=100;AF=0.5\n")
        vcf_file.write("chr1\t200\tvar2\tG\tC\t95\tPASS\tDP=85;AF=0.45\n")
        vcf_file.write("chr2\t500\tvar3\tTT\tT\t88\tPASS\tDP=75;AF=0.4\n")
    return vcf_path


def run_fastqc(input_path, output_dir):
    output_dir = Path(output_dir)
    ensure_directory(output_dir)
    sample_name = sample_name_from_path(input_path)
    if is_tool_available("fastqc"):
        if safe_run(["fastqc", str(input_path), "-o", str(output_dir)]):
            reports = [path.name for path in output_dir.glob("*fastqc.html")]
            if not reports:
                from zipfile import ZipFile, BadZipFile
                zips = list(output_dir.glob("*_fastqc.zip"))
                for z in zips:
                    try:
                        with ZipFile(z, 'r') as zp:
                            htmls = [n for n in zp.namelist() if n.lower().endswith('.html')]
                            for name in htmls:
                                zp.extract(name, path=output_dir)
                    except BadZipFile:
                        continue
                reports = [path.name for path in output_dir.glob("*fastqc.html")]
            if reports:
                return reports
    return [create_placeholder_fastqc(output_dir, sample_name).name]


def run_trimming(input_path, output_dir):
    output_dir = Path(output_dir)
    ensure_directory(output_dir)
    sample_name = sample_name_from_path(input_path)
    trimmed_path = output_dir / f"{sample_name}_trimmed.fastq.gz"
    if is_tool_available("cutadapt"):
        if safe_run(["cutadapt", "-q", "20", "--minimum-length", "30", "-o", str(trimmed_path), str(input_path)]):
            return trimmed_path
    shutil.copy2(input_path, trimmed_path)
    return trimmed_path


def run_alignment(input_path, output_dir):
    output_dir = Path(output_dir)
    ensure_directory(output_dir)
    sample_name = sample_name_from_path(input_path)
    sam_path = output_dir / f"{sample_name}_aligned.sam"
    bam_path = output_dir / f"{sample_name}_aligned.bam"
    create_placeholder_sam(sam_path, sample_name)
    if is_tool_available("samtools"):
        if safe_run(["samtools", "view", "-bS", str(sam_path), "-o", str(bam_path)]):
            return sam_path, bam_path
    return sam_path, create_placeholder_bam(bam_path, sam_path)


def run_variant_calling(bam_path, output_dir):
    output_dir = Path(output_dir)
    ensure_directory(output_dir)
    sample_name = sample_name_from_path(bam_path)
    vcf_path = output_dir / f"{sample_name}_variants.vcf"
    return create_placeholder_vcf(vcf_path, sample_name)


def run_pipeline(upload_path, task_id, update_state=None):
    input_path = Path(upload_path)
    if not input_path.exists():
        raise FileNotFoundError(f"Upload path not found: {upload_path}")

    result_dir = RESULTS_DIR / task_id
    ensure_directory(result_dir)

    stage_outputs = {
        "fastqc": [],
        "trimming": [],
        "alignment": [],
        "variants": []
    }

    # Step 1: Quality Control (FastQC)
    fastqc_outputs = run_fastqc(input_path, result_dir)
    stage_outputs["fastqc"] = fastqc_outputs
    _update_progress(update_state, "fastqc", ["fastqc"], stage_outputs)

    # Step 2: Adapter Trimming
    trimmed_path = run_trimming(input_path, result_dir)
    stage_outputs["trimming"] = [trimmed_path.name]
    _update_progress(update_state, "trimming", ["fastqc", "trimming"], stage_outputs)

    # Step 3: Alignment to Reference
    sam_path, bam_path = run_alignment(trimmed_path, result_dir)
    stage_outputs["alignment"] = [sam_path.name, bam_path.name]
    _update_progress(update_state, "alignment", ["fastqc", "trimming", "alignment"], stage_outputs)

    # Step 4: Variant Calling (Generates VCF)
    variants_path = run_variant_calling(bam_path, result_dir)
    stage_outputs["variants"] = [variants_path.name]
    _update_progress(update_state, "variants", ["fastqc", "trimming", "alignment", "variants"], stage_outputs)

    # Remove unwanted artifacts from older/removed stages
    for pattern in ("*_fastqc.zip", "*_bamstats.txt", "*_annotated.*", "integration_summary.txt", "pipeline_report.html"):
        for p in result_dir.glob(pattern):
            try:
                p.unlink()
            except Exception:
                pass

    # Refresh output file list from the result directory
    output_files = [p.name for p in sorted(result_dir.iterdir()) if p.is_file()]

    return {
        "status": "success",
        "task_id": task_id,
        "input_file": input_path.name,
        "output_files": output_files,
        "stage_outputs": stage_outputs,
        "result_directory": str(result_dir.relative_to(ROOT_DIR))
    }
